blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
empty_item_single_line = true
format_code_in_doc_comments = true
format_strings = true
imports_layout = "HorizontalVertical"
reorder_impl_items = true
group_imports = "StdExternalCrate"
wrap_comments = true